"""Switch theme_choice to JSON

Revision ID: 55ddf09bf3ed
Revises: d1a8a4b0bd40
Create Date: 2025-05-24 17:12:15.629051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ddf09bf3ed'
down_revision: Union[str, None] = 'd1a8a4b0bd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
