"""Add journey_start to users

Revision ID: ddf17de157be
Revises: 
Create Date: 2025-05-20 17:05:43.944539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf17de157be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('journey_start_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('journal_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('circle_message_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_journal_entry', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_circle_msg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_circle_msg')
    op.drop_column('users', 'last_journal_entry')
    op.drop_column('users', 'circle_message_count')
    op.drop_column('users', 'journal_count')
    op.drop_column('users', 'journey_start_date')
    # ### end Alembic commands ###
