"""Add user connections

Revision ID: 07005572dfc8
Revises: 7c5226bd5872
Create Date: 2025-06-12 17:38:31.390783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07005572dfc8'
down_revision = '7c5226bd5872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_connections')
    # ### end Alembic commands ###
