"""📥 Add read flag to CircleMessage

Revision ID: 232f5eefa044
Revises: f02c062464ee
Create Date: 2025-05-29 18:02:25.576646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232f5eefa044'
down_revision = 'f02c062464ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_messages', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###
