"""Add recipient_tag to WishingWellMessage

Revision ID: 408465ef1483
Revises: f5f7c3203742
Create Date: 2025-05-31 16:04:16.103046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408465ef1483'
down_revision = 'f5f7c3203742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishing_well_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_tag', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishing_well_messages', schema=None) as batch_op:
        batch_op.drop_column('recipient_tag')

    # ### end Alembic commands ###
