"""Add show_journey_publicly field

Revision ID: 4deccca89a94
Revises: c3047794692a
Create Date: 2025-05-24 18:24:52.535426
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4deccca89a94'
down_revision = 'c3047794692a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_journey_publicly', sa.Boolean(), nullable=True))

    # Manual type conversion for existing string → JSON
    op.execute('ALTER TABLE users ALTER COLUMN theme_choice TYPE JSON USING theme_choice::json')


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('theme_choice',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('show_journey_publicly')


