"""🚀 Add has_completed_onboarding field to User

Revision ID: 4f3cda3f8502
Revises: 942d625a4cf0
Create Date: 2025-05-26 16:10:24.513950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3cda3f8502'
down_revision = '942d625a4cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_completed_onboarding', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_completed_onboarding')

    # ### end Alembic commands ###
