"""🧪 HeroProfile: added debug_field

Revision ID: 618b75fad757
Revises: 
Create Date: 2025-05-25 16:54:33.243942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618b75fad757'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debug_field', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_profiles', schema=None) as batch_op:
        batch_op.drop_column('debug_field')

    # ### end Alembic commands ###
