"""📬 Add mailbox and wishing well message models

Revision ID: 7c5226bd5872
Revises: df7519c65f7e
Create Date: 2025-06-11 17:09:07.268949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5226bd5872'
down_revision = 'df7519c65f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('well_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('message_type', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('well_messages', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('message_type')
        batch_op.drop_column('sender')

    # ### end Alembic commands ###
