"""Add summary_text to UserQuestEntry

Revision ID: 8e1b68c84c90
Revises: 333d4ed6d963
Create Date: 2025-05-23 18:45:55.260780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1b68c84c90'
down_revision = '333d4ed6d963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quest_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quest_entries', schema=None) as batch_op:
        batch_op.drop_column('summary_text')

    # ### end Alembic commands ###
