"""🔑 Add is_admin flag to User model

Revision ID: 942d625a4cf0
Revises: 1e4fdb5b605a
Create Date: 2025-05-26 14:28:20.193274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942d625a4cf0'
down_revision = '1e4fdb5b605a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
