"""Add sender_role to QueryHistory

Revision ID: a8e286ab339c
Revises: 07005572dfc8
Create Date: 2025-06-13 10:25:55.920438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e286ab339c'
down_revision = '07005572dfc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_history', schema=None) as batch_op:
        batch_op.drop_column('sender_role')

    # ### end Alembic commands ###
