"""Add resurgitag to User model

Revision ID: cd668837e664
Revises: c3047794692a
Create Date: 2025-05-23 20:31:19.050586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd668837e664'
down_revision = 'c3047794692a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resurgitag', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(None, ['resurgitag'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('resurgitag')

    # ### end Alembic commands ###
