"""Add first_quest_complete field to User

Revision ID: d8364779970d
Revises: c91627c5f13c
Create Date: 2025-06-19 20:37:06.077443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8364779970d'
down_revision = 'c91627c5f13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_quest_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('first_quest_complete')

    # ### end Alembic commands ###
